### PR TITLE
Initialized to use tito.

### PR DESCRIPTION
**Pull request by jmrodri**
* initial rpm spec
* python3: use print()
* use 3.11 which is in fedora 25
* use module prefix
* remove unused dependencies
* add setuptools & devel
* add pip buildrequires
* add releasers
* update releasers for temporary repos

### CODE REVIEW

**Comment by jmrodri** [comment]
TEST
------
* tag (DO NOT PUSH IT)
```
$ tito tag
Tagging new version of ansibleapp: untagged -> 0.1.1-1
Created tag: ansibleapp-0.1.1-1
   View: git show HEAD
   Undo: tito tag -u
   Push: git push origin && git push origin ansibleapp-0.1.1-1
```

**Comment by jmrodri** [comment]
TEST BUILD
---------------------
```
$ tito build --offline --rpm
Building package [ansibleapp-0.1.1-1]
Wrote: /tmp/tito/ansibleapp-0.1.1.tar.gz

Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.ziMbiC
+ umask 022
+ cd /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILD
+ cd /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILD
+ rm -rf ansibleapp-0.1.1
+ /usr/bin/gzip -dc /tmp/tito/rpmbuild-ansibleappdyii4alq/SOURCES/ansibleapp-0.1.1.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd ansibleapp-0.1.1
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.so0lGR
+ umask 022
+ cd /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILD
+ cd ansibleapp-0.1.1
+ /usr/bin/python3 setup.py build
running build
running build_py
creating build
creating build/lib
creating build/lib/ansibleapp
copying src/ansibleapp/engine.py -> build/lib/ansibleapp
copying src/ansibleapp/cli.py -> build/lib/ansibleapp
copying src/ansibleapp/__init__.py -> build/lib/ansibleapp
creating build/lib/ansibleapp/dat
copying src/ansibleapp/dat/ex.Dockerfile -> build/lib/ansibleapp/dat
+ exit 0
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.XmC4e8
+ umask 022
+ cd /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILD
+ '[' /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64 '!=' / ']'
+ rm -rf /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64
++ dirname /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64
+ mkdir -p /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT
+ mkdir /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64
+ cd ansibleapp-0.1.1
+ rm -rf /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64
+ /usr/bin/python3 setup.py install -O1 --skip-build --root /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64
running install
running install_lib
creating /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64
creating /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64/usr
creating /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64/usr/lib
creating /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64/usr/lib/python3.5
creating /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64/usr/lib/python3.5/site-packages
creating /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64/usr/lib/python3.5/site-packages/ansibleapp
creating /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64/usr/lib/python3.5/site-packages/ansibleapp/dat
copying build/lib/ansibleapp/dat/ex.Dockerfile -> /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64/usr/lib/python3.5/site-packages/ansibleapp/dat
copying build/lib/ansibleapp/__init__.py -> /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64/usr/lib/python3.5/site-packages/ansibleapp
copying build/lib/ansibleapp/cli.py -> /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64/usr/lib/python3.5/site-packages/ansibleapp
copying build/lib/ansibleapp/engine.py -> /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64/usr/lib/python3.5/site-packages/ansibleapp
byte-compiling /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64/usr/lib/python3.5/site-packages/ansibleapp/__init__.py to __init__.cpython-35.pyc
byte-compiling /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64/usr/lib/python3.5/site-packages/ansibleapp/cli.py to cli.cpython-35.pyc
byte-compiling /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64/usr/lib/python3.5/site-packages/ansibleapp/engine.py to engine.cpython-35.pyc
writing byte-compilation script '/tmp/tmps3vtojpu.py'
/usr/bin/python3 -O /tmp/tmps3vtojpu.py
removing /tmp/tmps3vtojpu.py
running install_egg_info
running egg_info
creating src/ansibleapp.egg-info
writing requirements to src/ansibleapp.egg-info/requires.txt
writing top-level names to src/ansibleapp.egg-info/top_level.txt
writing dependency_links to src/ansibleapp.egg-info/dependency_links.txt
writing src/ansibleapp.egg-info/PKG-INFO
writing entry points to src/ansibleapp.egg-info/entry_points.txt
writing manifest file 'src/ansibleapp.egg-info/SOURCES.txt'
reading manifest file 'src/ansibleapp.egg-info/SOURCES.txt'
writing manifest file 'src/ansibleapp.egg-info/SOURCES.txt'
Copying src/ansibleapp.egg-info to /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64/usr/lib/python3.5/site-packages/ansibleapp-0.1.1-py3.5.egg-info
running install_scripts
Installing ansibleapp script to /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64/usr/bin
+ /usr/lib/rpm/find-debuginfo.sh --strict-build-id -m --run-dwz --dwz-low-mem-die-limit 10000000 --dwz-max-die-limit 110000000 /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILD/ansibleapp-0.1.1
find: 'debug': No such file or directory
+ /usr/lib/rpm/check-rpaths /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/brp-compress
+ /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
Bytecompiling .py files below /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64/usr/lib/python3.5 using /usr/bin/python3.5
+ /usr/lib/rpm/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-java-repack-jars
Processing files: ansibleapp-0.1.1-1.fc25.noarch
Provides: ansibleapp = 0.1.1-1.fc25 python3.5dist(ansibleapp) = 0.1.1 python3dist(ansibleapp) = 0.1.1
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires: /usr/bin/python3 python(abi) = 3.5
Checking for unpackaged file(s): /usr/lib/rpm/check-files /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64
Wrote: /tmp/tito/ansibleapp-0.1.1-1.fc25.src.rpm
Wrote: /tmp/tito/noarch/ansibleapp-0.1.1-1.fc25.noarch.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.lrWdCu
+ umask 022
+ cd /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILD
+ cd ansibleapp-0.1.1
+ rm -rf /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILDROOT/ansibleapp-0.1.1-1.fc25.x86_64
+ exit 0
Executing(--clean): /bin/sh -e /var/tmp/rpm-tmp.fVnVZQ
+ umask 022
+ cd /tmp/tito/rpmbuild-ansibleappdyii4alq/BUILD
+ rm -rf ansibleapp-0.1.1
+ exit 0

Successfully built: /tmp/tito/ansibleapp-0.1.1-1.fc25.src.rpm /tmp/tito/noarch/ansibleapp-0.1.1-1.fc25.noarch.rpm
```

**Comment by jmrodri** [comment]
TEST LIST RELEASE
-----------------------------
```
$ tito release --list
Available release targets:
  yum-el7-x86_64
  yum-el6-x86_64
  yum-f25-x86_64
```

**Comment by jmrodri** [comment]
TEST RELEASE
--------------------------
This might not work because I'm the only ont with access to these repos at this time. But here's the output of the release:
```
[jesusr@speed3 ansibleapp{addtito}]$ RSYNC_USERNAME=jmrodri tito release --offline --all-starting-with=yum
Will release to the following targets: yum-el7-x86_64, yum-el6-x86_64, yum-f25-x86_64
Releasing to target: yum-el7-x86_64
Working in: /tmp/tito/release-ansibleappueh_y87x
Wrote: /tmp/tito/ansibleapp-0.1.1.tar.gz
Wrote: /tmp/tito/ansibleapp-0.1.1.tar.gz

Wrote: /tmp/tito/ansibleapp-0.1.1-1.el7.src.rpm


Creating rpms for ansibleapp-0.1.1 in mock: epel-7-x86_64
Using srpm: /tmp/tito/ansibleapp-0.1.1-1.el7.src.rpm
Initializing mock...
Installing deps in mock...
Building RPMs in mock...
Wrote:
  /tmp/tito/ansibleapp-0.1.1-1.el7.centos.noarch.rpm
RSYNC_USERNAME set, using rsync username: jmrodri
rsync -rlvz jmrodri@fedorapeople.org:/srv/repos/jmrodri/ansibleapp/epel-7/x86_64 /tmp/tito/yumrepo-o0y78ba4
copy: /tmp/tito/ansibleapp-0.1.1-1.el7.centos.noarch.rpm > /tmp/tito/yumrepo-o0y78ba4
Refreshing yum repodata...                                                                                                                                                           
rsync -rlvz --delete /tmp/tito/yumrepo-vr3klgb5/ jmrodri@fedorapeople.org:/srv/repos/jmrodri/ansibleapp/epel-7Server/x86_64
Releasing to target: yum-el6-x86_64
Working in: /tmp/tito/release-ansibleapphov27xqh
Wrote: /tmp/tito/ansibleapp-0.1.1.tar.gz
Wrote: /tmp/tito/ansibleapp-0.1.1.tar.gz

Wrote: /tmp/tito/ansibleapp-0.1.1-1.el6.src.rpm


Creating rpms for ansibleapp-0.1.1 in mock: epel-6-x86_64
Using srpm: /tmp/tito/ansibleapp-0.1.1-1.el6.src.rpm
Initializing mock...
Installing deps in mock...
Building RPMs in mock...
Wrote:
  /tmp/tito/ansibleapp-0.1.1-1.el6.noarch.rpm
RSYNC_USERNAME set, using rsync username: jmrodri
rsync -rlvz jmrodri@fedorapeople.org:/srv/repos/jmrodri/ansibleapp/epel-6/x86_64 /tmp/tito/yumrepo-yllr34b4
copy: /tmp/tito/ansibleapp-0.1.1-1.el6.noarch.rpm > /tmp/tito/yumrepo-yllr34b4
Refreshing yum repodata...
rsync -rlvz --delete /tmp/tito/yumrepo-yllr34b4/ jmrodri@fedorapeople.org:/srv/repos/jmrodri/ansibleapp/epel-6/x86_64
RSYNC_USERNAME set, using rsync username: jmrodri
rsync -rlvz jmrodri@fedorapeople.org:/srv/repos/jmrodri/ansibleapp/epel-6Server/x86_64 /tmp/tito/yumrepo-rnku0ils
copy: /tmp/tito/ansibleapp-0.1.1-1.el6.noarch.rpm > /tmp/tito/yumrepo-rnku0ils
Refreshing yum repodata...
rsync -rlvz --delete /tmp/tito/yumrepo-rnku0ils/ jmrodri@fedorapeople.org:/srv/repos/jmrodri/ansibleapp/epel-6Server/x86_64
Releasing to target: yum-f25-x86_64
Working in: /tmp/tito/release-ansibleapp7xj8saxx
Wrote: /tmp/tito/ansibleapp-0.1.1.tar.gz
Wrote: /tmp/tito/ansibleapp-0.1.1.tar.gz

Wrote: /tmp/tito/ansibleapp-0.1.1-1.fc25.src.rpm


Creating rpms for ansibleapp-0.1.1 in mock: fedora-25-x86_64
Using srpm: /tmp/tito/ansibleapp-0.1.1-1.fc25.src.rpm
Initializing mock...
Installing deps in mock...
Building RPMs in mock...
Wrote:
  /tmp/tito/ansibleapp-0.1.1-1.fc25.noarch.rpm
RSYNC_USERNAME set, using rsync username: jmrodri
rsync -rlvz jmrodri@fedorapeople.org:/srv/repos/jmrodri/ansibleapp/fedora-25/x86_64 /tmp/tito/yumrepo-85y42_8z
copy: /tmp/tito/ansibleapp-0.1.1-1.fc25.noarch.rpm > /tmp/tito/yumrepo-85y42_8z
Refreshing yum repodata...
rsync -rlvz --delete /tmp/tito/yumrepo-85y42_8z/ jmrodri@fedorapeople.org:/srv/repos/jmrodri/ansibleapp/fedora-25/x86_64
```

**Comment by jmrodri** [comment]
TEST BUILDING WITH MOCK
-------------------------------------------
This assumes you have mock installed AND your user is in the ```mock``` group.

```
$ tito build --builder mock --arg mock=fedora-25-x86_64 --test --rpm
Building package [ansibleapp-0.1.1-1]
Creating rpms for ansibleapp-git-0.8941143 in mock: fedora-25-x86_64
Wrote: /tmp/tito/ansibleapp-git-0.8941143.tar.gz

Wrote: /tmp/tito/ansibleapp-0.1.1-1.git.0.8941143.fc25.src.rpm


Using srpm: /tmp/tito/ansibleapp-0.1.1-1.git.0.8941143.fc25.src.rpm
Initializing mock...
Installing deps in mock...
Building RPMs in mock...
Wrote:
  /tmp/tito/ansibleapp-0.1.1-1.git.0.8941143.fc25.noarch.rpm
```

**Comment by jmrodri** [comment]
OUTPUT OF THE RPM
----------------------------
Here is the output of the rpm. I think next step is to create an ```ansibleapp-doc``` package to separate the docs out.

```
$ rpm -qlp /tmp/tito/ansibleapp-0.1.1-1.git.0.8941143.fc25.noarch.rpm
/usr/bin/ansibleapp
/usr/lib/python3.5/site-packages/ansibleapp
/usr/lib/python3.5/site-packages/ansibleapp-0.1.1-py3.5.egg-info
/usr/lib/python3.5/site-packages/ansibleapp-0.1.1-py3.5.egg-info/PKG-INFO
/usr/lib/python3.5/site-packages/ansibleapp-0.1.1-py3.5.egg-info/SOURCES.txt
/usr/lib/python3.5/site-packages/ansibleapp-0.1.1-py3.5.egg-info/dependency_links.txt
/usr/lib/python3.5/site-packages/ansibleapp-0.1.1-py3.5.egg-info/entry_points.txt
/usr/lib/python3.5/site-packages/ansibleapp-0.1.1-py3.5.egg-info/requires.txt
/usr/lib/python3.5/site-packages/ansibleapp-0.1.1-py3.5.egg-info/top_level.txt
/usr/lib/python3.5/site-packages/ansibleapp/__init__.py
/usr/lib/python3.5/site-packages/ansibleapp/__pycache__
/usr/lib/python3.5/site-packages/ansibleapp/__pycache__/__init__.cpython-35.opt-1.pyc
/usr/lib/python3.5/site-packages/ansibleapp/__pycache__/__init__.cpython-35.pyc
/usr/lib/python3.5/site-packages/ansibleapp/__pycache__/cli.cpython-35.opt-1.pyc
/usr/lib/python3.5/site-packages/ansibleapp/__pycache__/cli.cpython-35.pyc
/usr/lib/python3.5/site-packages/ansibleapp/__pycache__/engine.cpython-35.opt-1.pyc
/usr/lib/python3.5/site-packages/ansibleapp/__pycache__/engine.cpython-35.pyc
/usr/lib/python3.5/site-packages/ansibleapp/cli.py
/usr/lib/python3.5/site-packages/ansibleapp/dat
/usr/lib/python3.5/site-packages/ansibleapp/dat/ex.Dockerfile
/usr/lib/python3.5/site-packages/ansibleapp/engine.py
```

**Comment by jmrodri** [comment]
INSTALLED RPM
---------------------
Build and install:
```
$ tito build --test --rpm -i
WARNING: unable to lookup latest package tag, building untagged test project
WARNING: .tito/packages/ansibleapp doesn't exist in git, using current directory
Building package [ansibleapp-0.1.0-1]
Wrote: /tmp/tito/ansibleapp-git-18.54b568b.tar.gz

Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.NJPstK
....
Successfully built: /tmp/tito/ansibleapp-0.1.0-1.git.18.54b568b.fc25.src.rpm /tmp/tito/noarch/ansibleapp-0.1.0-1.git.18.54b568b.fc25.noarch.rpm
Auto-installing packages:
sudo dnf install -C -y /tmp/tito/noarch/ansibleapp-0.1.0-1.git.18.54b568b.fc25.noarch.rpm
BDB2053 Freeing read locks for locker 0xcc: 32687/139957693978368
BDB2053 Freeing read locks for locker 0xce: 32687/139957693978368
Last metadata expiration check: 0:51:28 ago on Tue Feb 21 22:37:36 2017.
Dependencies resolved.
================================================================================
 Package       Arch      Version                          Repository       Size
================================================================================
Installing:
 ansibleapp    noarch    0.1.0-1.git.18.54b568b.fc25      @commandline     15 k

Transaction Summary
================================================================================
Install  1 Package

Total size: 15 k
Installed size: 21 k
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Installing  : ansibleapp-0.1.0-1.git.18.54b568b.fc25.noarch               1/1 
  Verifying   : ansibleapp-0.1.0-1.git.18.54b568b.fc25.noarch               1/1 

Installed:
  ansibleapp.noarch 0.1.0-1.git.18.54b568b.fc25                                 

Complete!
```
Did the app get installed?
```
$ which ansibleapp
/usr/bin/ansibleapp
```

It runs
```
$ ansibleapp --help
usage: ansibleapp [-h] [--debug] [--project BASE_PATH]
                  {help,build,prepare} ...

ansibleapp tooling forassisting in building and packaging ansibleapps.

optional arguments:
  -h, --help            show this help message and exit
  --debug               Enable debug output
  --project BASE_PATH, -p BASE_PATH
                        Specify a path to your project. Defaults to CWD.

subcommand:
  {help,build,prepare}
    help                Display this help message
    build               Build and package ansibleapp container
    prepare             Prepare an ansible-container project for ansibleapp
                        packaging
```

**Comment by eriknelson** [comment]
Why is the travis build trying to find a Rakefile?

```
[0K$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

travis_time:end:03a746d0:start=1487736822187841517,finish=1487736822325986896,duration=138145379
[0K
[31;1mThe command "rake" exited with 1.[0m

Done. Your build exited with 1.
```

Anyways, this all looks good to me, ACK. Thanks @jmrodri

**Comment by jmontleon** [comment]
ACK

**Comment by jmrodri** [comment]
@eriknelson I needed to rebase off master branch. .travis.yml was in master but not my branch. Fixed. GREEN TESTS.

**Pull request merged**
